version: '3'

services:
  web:
    build: .
    command: bash /apps/deployment/startup/app.sh
    ports:
      - "8086:8080"
    volumes:
      - ./deployment/settings/env/:/apps/settings/env/
      - ./deployment/settings/secrets/:/apps/settings/secrets/
      - ./deployment/conf:/apps/deployment/conf/
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/apps/deployment/client.json
  test:
    build: .
    command: bash /apps/deployment/startup/test.sh
    volumes:
      - ./deployment/settings/env:/apps/settings/env
      - ./deployment/settings/secrets:/apps/settings/secrets
      - ./deployment/settings/test:/apps/settings/test